version: '3.3'

networks:
  django-react-todo-network:
    driver: bridge

services:
  db:
    image: postgres:11-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - "5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: secret12345
      POSTGRES_DB: todo
    restart: on-failure
    networks:
      - django-react-todo-network
  django:
    build: ./backend
    command: sh -c "python manage.py makemigrations &&
                    python manage.py migrate &&
                    python manage.py collectstatic --noinput &&
                    gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - web-django:/app/backend
      - web-static:/app/backend/static
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: on-failure
    networks:
      - django-react-todo-network
  frontend:
    build: ./frontend
    command: ["npm", "start"]
    volumes:
      - ./frontend:/app/frontend
      - node-modules:/app/frontend/node_modules
    ports:
      - "3000:3000"
    restart: on-failure
    networks:
      - django-react-todo-network

volumes:
  node-modules:
  postgres_data:
  web-django:
  web-static: